--STEP 1

TRUNCATE TABLE al_finance.fin_tne_expense_fs;
--STEP 2

INSERT INTO al_finance.fin_tne_expense_fs 
(
	batch_constant,
	batch_id,
	batch_dt,
	batch_seq_nbr,
	emp_id,
	emp_last_name,
	emp_first_name,
	emp_middle_name,
	emp_grp_cntry,
	emp_org_unit_log_system,
	emp_org_unit_glid_compny_cd,
	emp_org_unit_cist_obj_type,
	emp_org_unit_cost_obj,
	emp_org_unit_5,
	emp_org_unit_6,
	ach_bank_accnt_nbr,
	ach_bank_routing_nbr,
	journal_totl_adj_reclaim_tax,
	rep_id,
	rep_key,
	ledger_cd,
	reimb_alpha_ise_curncy,
	home_cntry_name,
	rep_submit_dt,
	rep_creation_dt,
	rep_paymnt_processing_dt,
	rep_name,
	rep_image_req,
	rep_vat_entry,
	rep_ta_entry,
	rep_total_post_amt,
	rep_total_approved_amt,
	rep_policy_name,
	rep_budget_accrual_dt,
	rep_org_unit_log_system,
	rep_org_unit_compny_cd,
	rep_org_unit_cost_obj_type,
	rep_org_unit_cost_obj,
	rep_org_unit_5,
	rep_org_unit_6,
	rep_custom_glid,
	rep_custom_adn_nbr,
	rep_custom_trip_type,
	rep_custom_destinatn,
	rep_custom_pl,
	rep_custom_6,
	rep_custom_emp_band,
	rep_custom_sso_id,
	rep_custom_dir_indir_flag,
	rep_custom_bt_order_nbr,
	rep_custom_field_rotator,
	rep_custom_on_site,
	rep_custom_bt_order_type,
	rep_custom_14,
	rep_custom_erp_expense_grp,
	rep_custom_expense_grp_cntry,
	rep_custom_vendor_id,
	rep_custom_18,
	rep_custom_19,
	rep_custom_20,
	rep_entry_id,
	rep_entry_txn_type,
	rep_entry_expense_type_name,
	rep_entry_txn_dt,
	rep_entry_curncy_cd,
	rep_entry_exchange_rt,
	rep_entry_exchange_rt_dir,
	rep_entry_personal_flag,
	rep_entry_desc,
	rep_entry_vendor_name,
	rep_entry_vendor_desc,
	rep_entry_receipt_recvd_flag,
	rep_entry_receipt_type,
	emp_attendee_total,
	spouse_attendee_total,
	business_attendee_total,
	rep_entry_org_unit_1,
	rep_entry_org_unit_2,
	rep_entry_org_unit_3,
	rep_entry_org_unit_4,
	rep_entry_org_unit_5,
	rep_entry_org_unit_6,
	rep_entry_custom_passenger_name,
	rep_entry_custom_class_of_svc,
	rep_entry_custom_phone_nbr,
	rep_entry_custom_invoice_nbr,
	rep_entry_custom_5,
	rep_entry_custom_6,
	rep_entry_custom_7,
	rep_entry_custom_8,
	rep_entry_custom_9,
	rep_entry_custom_10,
	rep_entry_custom_11,
	rep_entry_custom_12,
	rep_entry_custom_13,
	rep_entry_custom_14,
	rep_entry_custom_15,
	rep_entry_custom_16,
	rep_entry_custom_17,
	rep_entry_custom_18,
	rep_entry_custom_19,
	rep_entry_custom_20,
	rep_entry_custom_21,
	rep_entry_custom_22,
	rep_entry_custom_23,
	rep_entry_custom_24,
	rep_entry_custom_25,
	rep_entry_custom_26,
	rep_entry_custom_27,
	rep_entry_custom_28,
	rep_entry_custom_29,
	rep_entry_custom_30,
	rep_entry_custom_tax_deduct_amt,
	rep_entry_custom_non_tax_deduct_amt,
	rep_entry_custom_tax_deduct_vat_amt,
	rep_entry_custom_non_tax_deduct_vat_amt,
	rep_entry_custom_tax_reclaim_cntry,
	rep_entry_custom_36,
	rep_entry_custom_sub_from_gross,
	rep_entry_custom_vat_cd,
	rep_entry_custom_tax_reclaim_amt,
	rep_entry_custom_net_tax_amt,
	rep_entry_txn_amt,
	rep_entry_posted_amt,
	rep_entry_approved_amt,
	payment_type_cd,
	payment_cd,
	rep_pay_reimb_type,
	bill_dt,
	billed_cc_accnt_nbr,
	billed_cc_desc,
	cc_txn_jr_key,
	cc_txn_ref_nbr,
	cc_txn_cct_key,
	cc_txn_cct_type,
	cc_txn_id,
	cc_txn_amt,
	cc_txn_tax_amt,
	cc_txn_curncy_cd,
	cc_txn_posted_amt,
	cc_txn_posted_curncy_cd,
	cc_txn_dt,
	cc_txn_posted_dt,
	cc_txn_desc,
	cc_txn_master_card_cd,
	cc_txn_merchant_name,
	cc_txn_merchant_city,
	cc_txn_merchant_state,
	cc_txn_merchant_cntry_cd,
	cc_txn_merchant_ref_nbr,
	cc_txn_billing_type,
	billing_to_emp_curncy_exchange_rt,
	billing_amt,
	indv_cc_accnt_nbr,
	indv_cc_name,
	merchant_business,
	acquirer_ref_nbr,
	rep_entry_loctn_cntry_cd,
	rep_entry_loctn_cntry_sub_cd,
	rep_entry_foreign_domes_flg,
	market_cd,
	processor_ref_nbr,
	journl_payer_payment_type_name,
	journl_payer_payment_cd_name,
	journl_payee_payment_type_name,
	journl_payee_payment_cd_name,
	journl_accnt_cd,
	journl_dr_cr_flag,
	journl_amt,
	journl_key,
	car_business_dist,
	car_personal_dist,
	car_passenger_cnt,
	vehicle_id,
	cc_txn_sales,
	cc_vendor_name,
	ca_adv_req_amt,
	ca_adv_req_curncy_cd,
	ca_adv_req_curncy_num_cd,
	ca_adv_exchange_rt,
	ca_adv_curncy_cd,
	ca_adv_curncy_num_cd,
	ca_adv_issued_dt,
	ca_adv_payment_cd_name,
	ca_adv_txn_type,
	ca_adv_req_dt,
	ca_adv_key,
	ca_adv_payment_method,
	alloctn_key,
	alloctn_percentage,
	alloctn_custom_system,
	alloctn_custom_glid_compny_cd,
	alloctn_custom_cost_obj_type,
	alloctn_custom_cost_obj,
	alloctn_custom_5,
	alloctn_custom_6,
	alloctn_custom_7,
	alloctn_custom_8,
	alloctn_custom_9,
	alloctn_custom_10,
	alloctn_custom_11,
	alloctn_custom_12,
	alloctn_custom_13,
	alloctn_custom_14,
	alloctn_custom_15,
	alloctn_custom_16,
	alloctn_custom_17,
	alloctn_custom_18,
	alloctn_custom_19,
	alloctn_custom_20,
	journl_net_total_adj_tax,
	ta_reimb_type,
	ta_display_limit,
	ta_allowance_limit,
	allowable_threshold,
	ta_fixed_lodging_type,
	base_amt,
	allowance_amt,
	ta_fixed_overnight,
	ta_fixed_breakfast_flag,
	ta_fixed_lunch_flg,
	ta_fixed_dinner_flg,
	total_tax_adj_posted_amt,
	total_reclaim_adj_amt,
	tax_authority_name,
	tax_authority_label,
	rep_entry_tax_txn_amt,
	rep_entry_tax_posted_amt,
	tax_src,
	rep_entry_tax_reclaim_txn_amt,
	rep_entry_tax_reclaim_posted_amt,
	rep_entry_tax_cd,
	rep_entry_tax_reclaim_domestic_flag,
	rep_entry_tax_adj_amt,
	rep_entry_tax_relcaim_ajd_amt,
	rep_entry_tax_reclaim_cd,
	rep_entry_tax_reclaim_txn_adj_cd,
	rep_entry_tax_alloc_reclaim_cd,
	travel_req_id,
	travel_req_name,
	travel_req_total_posted_amt,
	travel_req_total_approved_amt,
	travel_req_start_dt,
	travel_req_end_dt,
	travel_req_auth_dt,
	rep_entry_total_tax_posted_amt,
	net_tax_amt,
	rep_entry_total_reclaim_adj_amt,
	net_adj_reclaim_amt,
	rep_entry_payment_type_name,
	card_prog_type_cd,
	statement_period_start_dt,
	statement_period_end_dt,
	cash_accnt_cd,
	liability_accnt_cd,
	estimated_payment_dt,
	funding_trace,
	req_disbursement_dt,
	ca_adv_name,
	future_use_1,
	future_use_2,
	future_use_3,
	future_use_4,
	emp_login_id,
	emp_email_address,
	emp_custom_glid,
	emp_custom_adn_nbr,
	emp_custom_type,
	emp_custom_job_func,
	emp_custom_pl,
	emp_custom_vehicle_allowance,
	emp_custom_band,
	emp_custom_sso_id,
	emp_custom_dir_indir_flag,
	emp_custom_regn,
	emp_custom_11,
	emp_custom_12,
	emp_custom_13,
	emp_custom_14,
	emp_custom_15,
	emp_custom_16,
	emp_custom_17,
	emp_custom_18,
	emp_custom_19,
	emp_custom_20,
	future_use_5,
	future_use_6,
	future_use_7,
	future_use_8,
	future_use_9,
	emp_bank_accnt_active_flag,
	emp_bank_accnt_type,
	emp_bank_accnt_name,
	emp_bank_name,
	emp_bank_branch_loctn,
	emp_bank_addr_line_1,
	emp_bank_addr_line_2,
	emp_bank_city,
	emp_bank_regn,
	emp_bank_postal_cd,
	emp_bank_cntry_cd,
	emp_bank_tax_id,
	emp_bank_resident_flag,
	emp_bank_accnt_status,
	emp_bank_accnt_curncy,
	future_use_10,
	future_use_11,
	future_use_12,
	future_use_13,
	future_use_14,
	personal_expenses,
	total_claimed_amt,
	emp_due_amt,
	compny_card_due_amt,
	not_approved_amt,
	compny_paid_amt,
	compny_due_amt,
	payment_confirmed_amt,
	emp_actual_due_amt,
	actual_due_compny_card_amt,
	report_type,
	tot_tax_adj_amt,
	net_adj_tax_amt,
	future_use_15,
	future_use_16,
	future_use_17,
	ca_adv_returns_amt,
	ca_adv_return_received,
	ca_adv_utilized_amt,
	future_use_18,
	future_use_19,
	future_use_20,
	future_use_21,
	rep_entry_locatn_city_name,
	billable_flag,
	rep_entr_loc_from,
	rep_entr_loc_to,
	rep_entr_loc_nm,
	rep_entry_cntry,
	rep_entry_state_prov,
	rep_entry_uuid,
	rep_entry_vendor_tax_id,
	future_use_22,
	future_use_23,
	future_use_24,
	future_use_25,
	alloc_total_tax_txn_amt,
	alloc_total_tax_posted_amt,
	alloc_total_tax_reclaim_txn_amt,
	alloc_total_tax_reclaim_posted_amt,
	alloc_total_tax_reclaim_txn_adj_amt,
	future_use_26,
	future_use_27,
	future_use_28,
	future_use_29,
	future_use_30,
	req_name,
	req_total_posted_amt,
	req_total_aproved_amt,
	req_start_dt,
	req_end_dt,
	req_authorized_dt,
	req_authorization_id,
	future_use_32,
	future_use_33,
	future_use_34,
	future_use_35,
	future_use_36,
	future_use_37,
	future_use_38,
	future_use_39,
	future_use_40,
	future_use_41,
	future_use_42,
	future_use_43,
	future_use_44,
	future_use_45,
	future_use_46,
	future_use_47,
	future_use_48,
	future_use_49,
	future_use_50,
	future_use_51,
	future_use_52,
	future_use_53,
	future_use_54,
	future_use_55,
	future_use_56,
	future_use_57,
	future_use_58,
	future_use_59,
	future_use_60,
	future_use_61,
	future_use_62,
	future_use_63,
	future_use_64,
	future_use_65,
	future_use_66,
	future_use_67,
	future_use_68,
	src_system_id,
	src_name,
	dl_ins_by,
	dl_upd_by,
	dl_ins_ts,
	dl_upd_ts 
)
SELECT
	batch_constant,
	batch_id,
	batch_dt,
	batch_seq_nbr,
	emp_id,
	emp_last_name,
	emp_first_name,
	emp_middle_name,
	emp_grp_cntry,
	emp_org_unit_log_system,
	emp_org_unit_glid_compny_cd,
	emp_org_unit_cist_obj_type,
	emp_org_unit_cost_obj,
	emp_org_unit_5,
	emp_org_unit_6,
	ach_bank_accnt_nbr,
	ach_bank_routing_nbr,
	journal_totl_adj_reclaim_tax,
	rep_id,
	rep_key,
	ledger_cd,
	reimb_alpha_ise_curncy,
	home_cntry_name,
	CASE WHEN rep_submit_dt='' THEN NULL ELSE rep_submit_dt::TIMESTAMP END,
	CASE WHEN rep_creation_dt='' THEN NULL ELSE rep_creation_dt::TIMESTAMP END,
	CASE WHEN rep_paymnt_processing_dt='' THEN NULL ELSE rep_paymnt_processing_dt::TIMESTAMP END,
	rep_name,
	rep_image_req,
	rep_vat_entry,
	rep_ta_entry,
	CASE WHEN rep_total_post_amt='' THEN NULL ELSE rep_total_post_amt::NUMERIC END,
	CASE WHEN rep_total_approved_amt='' THEN NULL ELSE rep_total_approved_amt::NUMERIC END,
	rep_policy_name,
	CASE WHEN rep_budget_accrual_dt='' THEN NULL ELSE rep_budget_accrual_dt::TIMESTAMP END,
	rep_org_unit_log_system,
	rep_org_unit_compny_cd,
	rep_org_unit_cost_obj_type,
	rep_org_unit_cost_obj,
	rep_org_unit_5,
	rep_org_unit_6,
	rep_custom_glid,
	rep_custom_adn_nbr,
	rep_custom_trip_type,
	rep_custom_destinatn,
	rep_custom_pl,
	rep_custom_6,
	rep_custom_emp_band,
	rep_custom_sso_id,
	rep_custom_dir_indir_flag,
	rep_custom_bt_order_nbr,
	rep_custom_field_rotator,
	rep_custom_on_site,
	rep_custom_bt_order_type,
	rep_custom_14,
	rep_custom_erp_expense_grp,
	rep_custom_expense_grp_cntry,
	rep_custom_vendor_id,
	rep_custom_18,
	rep_custom_19,
	rep_custom_20,
	rep_entry_id,
	rep_entry_txn_type,
	rep_entry_expense_type_name,
	CASE WHEN rep_entry_txn_dt='' THEN NULL ELSE rep_entry_txn_dt::TIMESTAMP END,
	rep_entry_curncy_cd,
	CASE WHEN rep_entry_exchange_rt='' THEN NULL ELSE rep_entry_exchange_rt::NUMERIC END,
	rep_entry_exchange_rt_dir,
	rep_entry_personal_flag,
	rep_entry_desc,
	rep_entry_vendor_name,
	rep_entry_vendor_desc,
	rep_entry_receipt_recvd_flag,
	rep_entry_receipt_type,
	emp_attendee_total,
	spouse_attendee_total,
	business_attendee_total,
	rep_entry_org_unit_1,
	rep_entry_org_unit_2,
	rep_entry_org_unit_3,
	rep_entry_org_unit_4,
	rep_entry_org_unit_5,
	rep_entry_org_unit_6,
	rep_entry_custom_passenger_name,
	rep_entry_custom_class_of_svc,
	rep_entry_custom_phone_nbr,
	rep_entry_custom_invoice_nbr,
	rep_entry_custom_5,
	rep_entry_custom_6,
	rep_entry_custom_7,
	rep_entry_custom_8,
	rep_entry_custom_9,
	rep_entry_custom_10,
	rep_entry_custom_11,
	rep_entry_custom_12,
	rep_entry_custom_13,
	rep_entry_custom_14,
	rep_entry_custom_15,
	rep_entry_custom_16,
	rep_entry_custom_17,
	rep_entry_custom_18,
	rep_entry_custom_19,
	rep_entry_custom_20,
	rep_entry_custom_21,
	rep_entry_custom_22,
	rep_entry_custom_23,
	rep_entry_custom_24,
	rep_entry_custom_25,
	rep_entry_custom_26,
	rep_entry_custom_27,
	rep_entry_custom_28,
	rep_entry_custom_29,
	rep_entry_custom_30,
	CASE WHEN rep_entry_custom_tax_deduct_amt='' THEN NULL ELSE rep_entry_custom_tax_deduct_amt::NUMERIC END,
	CASE WHEN rep_entry_custom_non_tax_deduct_amt='' THEN NULL ELSE rep_entry_custom_non_tax_deduct_amt::NUMERIC END,
	CASE WHEN rep_entry_custom_tax_deduct_vat_amt='' THEN NULL ELSE rep_entry_custom_tax_deduct_vat_amt::NUMERIC END,
	CASE WHEN rep_entry_custom_non_tax_deduct_vat_amt='' THEN NULL ELSE rep_entry_custom_non_tax_deduct_vat_amt::NUMERIC END,
	rep_entry_custom_tax_reclaim_cntry,
	rep_entry_custom_36,
	rep_entry_custom_sub_from_gross,
	rep_entry_custom_vat_cd,
	CASE WHEN rep_entry_custom_tax_reclaim_amt='' THEN NULL ELSE rep_entry_custom_tax_reclaim_amt::NUMERIC END,
	CASE WHEN rep_entry_custom_net_tax_amt='' THEN NULL ELSE rep_entry_custom_net_tax_amt::NUMERIC END,
	CASE WHEN rep_entry_txn_amt='' THEN NULL ELSE rep_entry_txn_amt::NUMERIC END,
	CASE WHEN rep_entry_posted_amt='' THEN NULL ELSE rep_entry_posted_amt::NUMERIC END,
	CASE WHEN rep_entry_approved_amt='' THEN NULL ELSE rep_entry_approved_amt::NUMERIC END,
	payment_type_cd,
	payment_cd,
	rep_pay_reimb_type,
	CASE WHEN bill_dt='' THEN NULL ELSE bill_dt::TIMESTAMP END,
	billed_cc_accnt_nbr,
	billed_cc_desc,
	cc_txn_jr_key,
	cc_txn_ref_nbr,
	cc_txn_cct_key,
	cc_txn_cct_type,
	cc_txn_id,
	CASE WHEN cc_txn_amt='' THEN NULL ELSE cc_txn_amt::NUMERIC END,
	CASE WHEN cc_txn_tax_amt='' THEN NULL ELSE cc_txn_tax_amt::NUMERIC END,
	cc_txn_curncy_cd,
	CASE WHEN cc_txn_posted_amt='' THEN NULL ELSE cc_txn_posted_amt::NUMERIC END,
	cc_txn_posted_curncy_cd,
	CASE WHEN cc_txn_dt='' THEN NULL ELSE cc_txn_dt::TIMESTAMP END,
	CASE WHEN cc_txn_posted_dt='' THEN NULL ELSE cc_txn_posted_dt::TIMESTAMP END,
	cc_txn_desc,
	cc_txn_master_card_cd,
	cc_txn_merchant_name,
	cc_txn_merchant_city,
	cc_txn_merchant_state,
	cc_txn_merchant_cntry_cd,
	cc_txn_merchant_ref_nbr,
	cc_txn_billing_type,
	CASE WHEN billing_to_emp_curncy_exchange_rt='' THEN NULL ELSE billing_to_emp_curncy_exchange_rt::NUMERIC END,
	CASE WHEN billing_amt='' THEN NULL ELSE billing_amt::NUMERIC END,
	indv_cc_accnt_nbr,
	indv_cc_name,
	merchant_business,
	acquirer_ref_nbr,
	rep_entry_loctn_cntry_cd,
	rep_entry_loctn_cntry_sub_cd,
	rep_entry_foreign_domes_flg,
	market_cd,
	processor_ref_nbr,
	journl_payer_payment_type_name,
	journl_payer_payment_cd_name,
	journl_payee_payment_type_name,
	journl_payee_payment_cd_name,
	journl_accnt_cd,
	journl_dr_cr_flag,
	CASE WHEN journl_amt='' THEN NULL ELSE journl_amt::NUMERIC END,
	journl_key,
	car_business_dist,
	car_personal_dist,
	car_passenger_cnt,
	vehicle_id,
	cc_txn_sales,
	cc_vendor_name,
	CASE WHEN ca_adv_req_amt='' THEN NULL ELSE ca_adv_req_amt::NUMERIC END,
	ca_adv_req_curncy_cd,
	ca_adv_req_curncy_num_cd,
	ca_adv_exchange_rt,
	ca_adv_curncy_cd,
	ca_adv_curncy_num_cd,
	CASE WHEN ca_adv_issued_dt='' THEN NULL ELSE ca_adv_issued_dt::TIMESTAMP END,
	ca_adv_payment_cd_name,
	ca_adv_txn_type,
	CASE WHEN ca_adv_req_dt='' THEN NULL ELSE ca_adv_req_dt::TIMESTAMP END,
	ca_adv_key,
	ca_adv_payment_method,
	alloctn_key,
	alloctn_percentage,
	alloctn_custom_system,
	alloctn_custom_glid_compny_cd,
	alloctn_custom_cost_obj_type,
	alloctn_custom_cost_obj,
	alloctn_custom_5,
	alloctn_custom_6,
	alloctn_custom_7,
	alloctn_custom_8,
	alloctn_custom_9,
	alloctn_custom_10,
	alloctn_custom_11,
	alloctn_custom_12,
	alloctn_custom_13,
	alloctn_custom_14,
	alloctn_custom_15,
	alloctn_custom_16,
	alloctn_custom_17,
	alloctn_custom_18,
	alloctn_custom_19,
	alloctn_custom_20,
	journl_net_total_adj_tax,
	ta_reimb_type,
	ta_display_limit,
	ta_allowance_limit,
	allowable_threshold,
	ta_fixed_lodging_type,
	CASE WHEN base_amt='' THEN NULL ELSE base_amt::NUMERIC END,
	CASE WHEN allowance_amt='' THEN NULL ELSE allowance_amt::NUMERIC END,
	ta_fixed_overnight,
	ta_fixed_breakfast_flag,
	ta_fixed_lunch_flg,
	ta_fixed_dinner_flg,
	CASE WHEN total_tax_adj_posted_amt='' THEN NULL ELSE total_tax_adj_posted_amt::NUMERIC END,
	CASE WHEN total_reclaim_adj_amt='' THEN NULL ELSE total_reclaim_adj_amt::NUMERIC END,
	tax_authority_name,
	tax_authority_label,
	CASE WHEN rep_entry_tax_txn_amt='' THEN NULL ELSE rep_entry_tax_txn_amt::NUMERIC END,
	CASE WHEN rep_entry_tax_posted_amt='' THEN NULL ELSE rep_entry_tax_posted_amt::NUMERIC END,
	tax_src,
	CASE WHEN rep_entry_tax_reclaim_txn_amt='' THEN NULL ELSE rep_entry_tax_reclaim_txn_amt::NUMERIC END,
	CASE WHEN rep_entry_tax_reclaim_posted_amt='' THEN NULL ELSE rep_entry_tax_reclaim_posted_amt::NUMERIC END,
	rep_entry_tax_cd,
	rep_entry_tax_reclaim_domestic_flag,
	CASE WHEN rep_entry_tax_adj_amt='' THEN NULL ELSE rep_entry_tax_adj_amt::NUMERIC END,
	CASE WHEN rep_entry_tax_relcaim_ajd_amt='' THEN NULL ELSE rep_entry_tax_relcaim_ajd_amt::NUMERIC END ,
	rep_entry_tax_reclaim_cd,
	rep_entry_tax_reclaim_txn_adj_cd,
	rep_entry_tax_alloc_reclaim_cd,
	travel_req_id,
	travel_req_name,
	CASE WHEN travel_req_total_posted_amt='' THEN NULL ELSE travel_req_total_posted_amt::NUMERIC END,
	CASE WHEN travel_req_total_approved_amt='' THEN NULL ELSE travel_req_total_approved_amt::NUMERIC END,
	CASE WHEN travel_req_start_dt='' THEN NULL ELSE travel_req_start_dt::TIMESTAMP END,
	CASE WHEN travel_req_end_dt='' THEN NULL ELSE travel_req_end_dt::TIMESTAMP END,
	CASE WHEN travel_req_auth_dt='' THEN NULL ELSE travel_req_auth_dt::TIMESTAMP END,
	CASE WHEN rep_entry_total_tax_posted_amt='' THEN NULL ELSE rep_entry_total_tax_posted_amt::NUMERIC END,
	CASE WHEN net_tax_amt='' THEN NULL ELSE net_tax_amt::NUMERIC END,
	CASE WHEN rep_entry_total_reclaim_adj_amt='' THEN NULL ELSE rep_entry_total_reclaim_adj_amt::NUMERIC END,
	CASE WHEN net_adj_reclaim_amt='' THEN NULL ELSE net_adj_reclaim_amt::NUMERIC END,
	rep_entry_payment_type_name,
	card_prog_type_cd,
	CASE WHEN statement_period_start_dt='' THEN NULL ELSE statement_period_start_dt::TIMESTAMP END,
	CASE WHEN statement_period_end_dt='' THEN NULL ELSE statement_period_end_dt::TIMESTAMP END,
	cash_accnt_cd,
	liability_accnt_cd,
	CASE WHEN estimated_payment_dt='' THEN NULL ELSE estimated_payment_dt::TIMESTAMP END,
	funding_trace,
	CASE WHEN req_disbursement_dt='' THEN NULL ELSE req_disbursement_dt::TIMESTAMP END,
	ca_adv_name,
	future_use_1,
	future_use_2,
	future_use_3,
	future_use_4,
	emp_login_id,
	emp_email_address,
	emp_custom_glid,
	emp_custom_adn_nbr,
	emp_custom_type,
	emp_custom_job_func,
	emp_custom_pl,
	emp_custom_vehicle_allowance,
	emp_custom_band,
	emp_custom_sso_id,
	emp_custom_dir_indir_flag,
	emp_custom_regn,
	emp_custom_11,
	emp_custom_12,
	emp_custom_13,
	emp_custom_14,
	emp_custom_15,
	emp_custom_16,
	emp_custom_17,
	emp_custom_18,
	emp_custom_19,
	emp_custom_20,
	future_use_5,
	future_use_6,
	future_use_7,
	future_use_8,
	future_use_9,
	emp_bank_accnt_active_flag,
	emp_bank_accnt_type,
	emp_bank_accnt_name,
	emp_bank_name,
	emp_bank_branch_loctn,
	emp_bank_addr_line_1,
	emp_bank_addr_line_2,
	emp_bank_city,
	emp_bank_regn,
	emp_bank_postal_cd,
	emp_bank_cntry_cd,
	emp_bank_tax_id,
	emp_bank_resident_flag,
	emp_bank_accnt_status,
	emp_bank_accnt_curncy,
	future_use_10,
	future_use_11,
	future_use_12,
	future_use_13,
	future_use_14,
	personal_expenses,
	CASE WHEN total_claimed_amt='' THEN NULL ELSE total_claimed_amt::NUMERIC END,
	CASE WHEN emp_due_amt='' THEN NULL ELSE emp_due_amt::NUMERIC END,
	CASE WHEN compny_card_due_amt='' THEN NULL ELSE compny_card_due_amt::NUMERIC END,
	CASE WHEN not_approved_amt='' THEN NULL ELSE not_approved_amt::NUMERIC END,
	CASE WHEN compny_paid_amt='' THEN NULL ELSE compny_paid_amt::NUMERIC END,
	CASE WHEN compny_due_amt='' THEN NULL ELSE compny_due_amt::NUMERIC END,
	CASE WHEN payment_confirmed_amt='' THEN NULL ELSE payment_confirmed_amt::NUMERIC END,
	CASE WHEN emp_actual_due_amt='' THEN NULL ELSE emp_actual_due_amt::NUMERIC END,
	CASE WHEN actual_due_compny_card_amt='' THEN NULL ELSE actual_due_compny_card_amt::NUMERIC END,
	report_type,
	CASE WHEN tot_tax_adj_amt='' THEN NULL ELSE tot_tax_adj_amt::NUMERIC END,
	CASE WHEN net_adj_tax_amt='' THEN NULL ELSE net_adj_tax_amt::NUMERIC END,
	future_use_15,
	future_use_16,
	future_use_17,
	CASE WHEN ca_adv_returns_amt='' THEN NULL ELSE ca_adv_returns_amt::NUMERIC END,
	ca_adv_return_received,
	CASE WHEN ca_adv_utilized_amt='' THEN NULL ELSE ca_adv_utilized_amt::NUMERIC END,
	future_use_18,
	future_use_19,
	future_use_20,
	future_use_21,
	rep_entry_locatn_city_name,
	billable_flag,
	rep_entr_loc_from,
	rep_entr_loc_to,
	rep_entr_loc_nm,
	rep_entry_cntry,
	rep_entry_state_prov,
	rep_entry_uuid,
	rep_entry_vendor_tax_id,
	future_use_22,
	future_use_23,
	future_use_24,
	future_use_25,
	CASE WHEN alloc_total_tax_txn_amt='' THEN NULL ELSE alloc_total_tax_txn_amt::NUMERIC END,
	CASE WHEN alloc_total_tax_posted_amt='' THEN NULL ELSE alloc_total_tax_posted_amt::NUMERIC END,
	CASE WHEN alloc_total_tax_reclaim_txn_amt='' THEN NULL ELSE alloc_total_tax_reclaim_txn_amt::NUMERIC END,
	CASE WHEN alloc_total_tax_reclaim_posted_amt='' THEN NULL ELSE alloc_total_tax_reclaim_posted_amt::NUMERIC END,
	CASE WHEN alloc_total_tax_reclaim_txn_adj_amt='' THEN NULL ELSE alloc_total_tax_reclaim_txn_adj_amt::NUMERIC END,
	future_use_26,
	future_use_27,
	future_use_28,
	future_use_29,
	future_use_30,
	req_name,
	CASE WHEN req_total_posted_amt='' THEN NULL ELSE req_total_posted_amt::NUMERIC END,
	CASE WHEN req_total_aproved_amt='' THEN NULL ELSE req_total_aproved_amt::NUMERIC END,
	CASE WHEN req_start_dt='' THEN NULL ELSE req_start_dt::TIMESTAMP END,
	CASE WHEN req_end_dt='' THEN NULL ELSE req_end_dt::TIMESTAMP END,
	CASE WHEN req_authorized_dt='' THEN NULL ELSE req_authorized_dt::TIMESTAMP END,
	req_authorization_id,
	future_use_32,
	future_use_33,
	future_use_34,
	future_use_35,
	future_use_36,
	future_use_37,
	future_use_38,
	future_use_39,
	future_use_40,
	future_use_41,
	future_use_42,
	future_use_43,
	future_use_44,
	future_use_45,
	future_use_46,
	future_use_47,
	future_use_48,
	future_use_49,
	future_use_50,
	future_use_51,
	future_use_52,
	future_use_53,
	future_use_54,
	future_use_55,
	future_use_56,
	future_use_57,
	future_use_58,
	future_use_59,
	future_use_60,
	future_use_61,
	future_use_62,
	future_use_63,
	future_use_64,
	future_use_65,
	future_use_66,
	future_use_67,
	future_use_68,
	batch_constant || '~' || batch_id || '~' || batch_dt || '~' || batch_seq_nbr,
	'CON',
	'fin_tne_mtd_etl_scripts~fin_tne_fact_stg',
	'fin_tne_mtd_etl_scripts~fin_tne_fact_stg',
	CURRENT_TIMESTAMP,
	CURRENT_TIMESTAMP
FROM
og_file_src.fin_tne_sae_extract sae;
