--STEP 1

DELETE FROM AL_FINANCE.FIN_TNE_ATTENDEE_DTL_F fact 
	using (select * from AL_FINANCE.FIN_TNE_ATTENDEE_DTL_FS STAGE ) stage
	where fact.src_system_id=stage.SRC_SYSTEM_ID;
--STEP 2

Insert into al_finance.FIN_TNE_ATTENDEE_DTL_F( 
batch_constant
,batch_id
,batch_dt
,batch_seq_nbr
,emp_id
,emp_last_name
,emp_first_name
,emp_mid_name
,emp_custom_21
,emp_org_unit_1
,emp_org_unit_2
,emp_org_unit_3
,emp_org_unit_4
,emp_org_unit_5
,emp_org_unit_6
,future_use_1
,future_use_2
,future_use_3
,rep_id
,rep_key
,ledger_cd
,rep_curncy_alpha_cd
,rep_home_cntry_name
,rep_submit_dt
,rep_user_defined_dt
,rep_proc_payment_dt
,rep_name
,rep_policy_name
,future_use_4
,rep_org_unit_1
,rep_org_unit_2
,rep_org_unit_3
,rep_org_unit_4
,rep_org_unit_5
,rep_org_unit_6
,rep_custom_1
,rep_custom_2
,rep_custom_3
,rep_custom_4
,rep_custom_5
,rep_custom_6
,rep_custom_7
,rep_custom_8
,rep_custom_9
,rep_custom_10
,rep_custom_11
,rep_custom_12
,rep_custom_13
,rep_custom_14
,rep_custom_15
,rep_custom_16
,vendor_id
,rep_custom_18
,rep_custom_19
,rep_custom_20
,rep_entry_id
,rep_entry_txn_type
,rep_entry_expense_type_name
,rep_entry_txn_dt
,rep_entry_curncy_cd
,rep_entry_exchange_rt
,dir_rep_entry_exchange_rt
,rep_entry_personal_flag
,rep_entry_desc
,rep_entry_vendor_name
,rep_entry_vendor_desc
,rep_entry_attendee_cnt
,rep_entry_org_unit_1
,rep_entry_org_unit_2
,rep_entry_org_unit_3
,rep_entry_org_unit_4
,rep_entry_org_unit_5
,rep_entry_org_unit_6
,rep_entry_custom_1
,rep_entry_custom_2
,rep_entry_custom_3
,rep_entry_custom_4
,rep_entry_custom_5
,rep_entry_custom_6
,rep_entry_custom_7
,rep_entry_custom_8
,rep_entry_custom_9
,rep_entry_custom_10
,rep_entry_custom_11
,rep_entry_custom_12
,rep_entry_custom_13
,rep_entry_custom_14
,rep_entry_custom_15
,rep_entry_custom_16
,rep_entry_custom_17
,rep_entry_custom_18
,rep_entry_custom_19
,rep_entry_custom_20
,rep_entry_custom_21
,rep_entry_custom_22
,rep_entry_custom_23
,rep_entry_custom_24
,rep_entry_custom_25
,rep_entry_custom_26
,rep_entry_custom_27
,rep_entry_custom_28
,rep_entry_custom_29
,rep_entry_custom_30
,rep_entry_custom_31
,rep_entry_custom_32
,rep_entry_custom_33
,rep_entry_custom_34
,rep_entry_custom_35
,rep_entry_custom_36
,rep_entry_custom_37
,rep_entry_custom_38
,rep_entry_custom_39
,rep_entry_custom_40
,rep_entry_txn_amt
,rep_entry_posted_amt
,rep_entry_approved_amt
,future_use_5
,attendee_key
,attendee_unique_idn
,attendee_type_name
,attendee_type_cd
,attendee_last_name
,attendee_first_name
,attendee_compny_name
,attendee_title
,attendee_ytd_amt
,attendee_prev_year_amt
,attendee_curncy_alpha_cd
,attendee_custom_1
,attendee_custom_2
,attendee_custom_3
,attendee_custom_4
,attendee_custom_5
,attendee_custom_6
,attendee_custom_7
,attendee_custom_8
,attendee_custom_9
,attendee_custom_10
,attendee_custom_11
,attendee_custom_12
,attendee_custom_13
,attendee_custom_14
,attendee_custom_15
,attendee_custom_16
,attendee_custom_17
,attendee_custom_18
,attendee_custom_19
,attendee_custom_20
,attendee_txn_amt
,reimbcurncy_attendee_apprvd_amt
,curncy_attendee_approved_amt
,attendee_instance_cnt
,attendee_amt_is_edited
,attendee_entry_custom_1
,attendee_entry_custom_2
,attendee_entry_custom_3
,attendee_entry_custom_4
,attendee_entry_custom_5
,attendee_midle_initial
,attendee_suffix
,expense_locatn_cntry_cd
,expense_locatn_state
,expense_locatn_city_name
,attendee_custom_21
,attendee_custom_22
,attendee_custom_23
,attendee_custom_24
,attendee_custom_25
,future_use_6
,future_use_7
,future_use_8
,future_use_9
,future_use_10
,future_use_11
,future_use_12
,future_use_13
,future_use_14
,future_use_15
,future_use_16
,future_use_17
,future_use_18
,future_use_19
,future_use_20
,future_use_21
,future_use_22
,future_use_23
,future_use_24
,future_use_25
,future_use_26
,future_use_27
,future_use_28
,future_use_29
,future_use_30
,future_use_31
,future_use_32
,future_use_33
,future_use_34
,future_use_35
,future_use_36
,future_use_37
,future_use_38
,future_use_39
,future_use_40
,future_use_41
,future_use_42
,future_use_43
,future_use_44
,future_use_45
,future_use_46
,future_use_47
,future_use_48
,future_use_49
,future_use_50
,future_use_51
,future_use_52
,future_use_53
,future_use_54
,future_use_55
,future_use_56
,future_use_57
,src_system_id
,src_name
,dl_ins_by
,dl_upd_by
,dl_ins_ts
,dl_upd_ts
)
select 
fs.batch_constant
,fs.batch_id
,fs.batch_dt
,fs.batch_seq_nbr
,fs.emp_id
,fs.emp_last_name
,fs.emp_first_name
,fs.emp_mid_name
,fs.emp_custom_21
,fs.emp_org_unit_1
,fs.emp_org_unit_2
,fs.emp_org_unit_3
,fs.emp_org_unit_4
,fs.emp_org_unit_5
,fs.emp_org_unit_6
,fs.future_use_1
,fs.future_use_2
,fs.future_use_3
,fs.rep_id
,fs.rep_key
,fs.ledger_cd
,fs.rep_curncy_alpha_cd
,fs.rep_home_cntry_name
,fs.rep_submit_dt
,fs.rep_user_defined_dt
,fs.rep_proc_payment_dt
,fs.rep_name
,fs.rep_policy_name
,fs.future_use_4
,fs.rep_org_unit_1
,fs.rep_org_unit_2
,fs.rep_org_unit_3
,fs.rep_org_unit_4
,fs.rep_org_unit_5
,fs.rep_org_unit_6
,fs.rep_custom_1
,fs.rep_custom_2
,fs.rep_custom_3
,fs.rep_custom_4
,fs.rep_custom_5
,fs.rep_custom_6
,fs.rep_custom_7
,fs.rep_custom_8
,fs.rep_custom_9
,fs.rep_custom_10
,fs.rep_custom_11
,fs.rep_custom_12
,fs.rep_custom_13
,fs.rep_custom_14
,fs.rep_custom_15
,fs.rep_custom_16
,fs.vendor_id
,fs.rep_custom_18
,fs.rep_custom_19
,fs.rep_custom_20
,fs.rep_entry_id
,fs.rep_entry_txn_type
,fs.rep_entry_expense_type_name
,fs.rep_entry_txn_dt
,fs.rep_entry_curncy_cd
,fs.rep_entry_exchange_rt
,fs.dir_rep_entry_exchange_rt
,fs.rep_entry_personal_flag
,fs.rep_entry_desc
,fs.rep_entry_vendor_name
,fs.rep_entry_vendor_desc
,fs.rep_entry_attendee_cnt
,fs.rep_entry_org_unit_1
,fs.rep_entry_org_unit_2
,fs.rep_entry_org_unit_3
,fs.rep_entry_org_unit_4
,fs.rep_entry_org_unit_5
,fs.rep_entry_org_unit_6
,fs.rep_entry_custom_1
,fs.rep_entry_custom_2
,fs.rep_entry_custom_3
,fs.rep_entry_custom_4
,fs.rep_entry_custom_5
,fs.rep_entry_custom_6
,fs.rep_entry_custom_7
,fs.rep_entry_custom_8
,fs.rep_entry_custom_9
,fs.rep_entry_custom_10
,fs.rep_entry_custom_11
,fs.rep_entry_custom_12
,fs.rep_entry_custom_13
,fs.rep_entry_custom_14
,fs.rep_entry_custom_15
,fs.rep_entry_custom_16
,fs.rep_entry_custom_17
,fs.rep_entry_custom_18
,fs.rep_entry_custom_19
,fs.rep_entry_custom_20
,fs.rep_entry_custom_21
,fs.rep_entry_custom_22
,fs.rep_entry_custom_23
,fs.rep_entry_custom_24
,fs.rep_entry_custom_25
,fs.rep_entry_custom_26
,fs.rep_entry_custom_27
,fs.rep_entry_custom_28
,fs.rep_entry_custom_29
,fs.rep_entry_custom_30
,fs.rep_entry_custom_31
,fs.rep_entry_custom_32
,fs.rep_entry_custom_33
,fs.rep_entry_custom_34
,fs.rep_entry_custom_35
,fs.rep_entry_custom_36
,fs.rep_entry_custom_37
,fs.rep_entry_custom_38
,fs.rep_entry_custom_39
,fs.rep_entry_custom_40
,fs.rep_entry_txn_amt
,fs.rep_entry_posted_amt
,fs.rep_entry_approved_amt
,fs.future_use_5
,fs.attendee_key
,fs.attendee_unique_idn
,fs.attendee_type_name
,fs.attendee_type_cd
,fs.attendee_last_name
,fs.attendee_first_name
,fs.attendee_compny_name
,fs.attendee_title
,fs.attendee_ytd_amt
,fs.attendee_prev_year_amt
,fs.attendee_curncy_alpha_cd
,fs.attendee_custom_1
,fs.attendee_custom_2
,fs.attendee_custom_3
,fs.attendee_custom_4
,fs.attendee_custom_5
,fs.attendee_custom_6
,fs.attendee_custom_7
,fs.attendee_custom_8
,fs.attendee_custom_9
,fs.attendee_custom_10
,fs.attendee_custom_11
,fs.attendee_custom_12
,fs.attendee_custom_13
,fs.attendee_custom_14
,fs.attendee_custom_15
,fs.attendee_custom_16
,fs.attendee_custom_17
,fs.attendee_custom_18
,fs.attendee_custom_19
,fs.attendee_custom_20
,fs.attendee_txn_amt
,fs.reimbcurncy_attendee_apprvd_amt
,fs.curncy_attendee_approved_amt
,fs.attendee_instance_cnt
,fs.attendee_amt_is_edited
,fs.attendee_entry_custom_1
,fs.attendee_entry_custom_2
,fs.attendee_entry_custom_3
,fs.attendee_entry_custom_4
,fs.attendee_entry_custom_5
,fs.attendee_midle_initial
,fs.attendee_suffix
,fs.expense_locatn_cntry_cd
,fs.expense_locatn_state
,fs.expense_locatn_city_name
,fs.attendee_custom_21
,fs.attendee_custom_22
,fs.attendee_custom_23
,fs.attendee_custom_24
,fs.attendee_custom_25
,fs.future_use_6
,fs.future_use_7
,fs.future_use_8
,fs.future_use_9
,fs.future_use_10
,fs.future_use_11
,fs.future_use_12
,fs.future_use_13
,fs.future_use_14
,fs.future_use_15
,fs.future_use_16
,fs.future_use_17
,fs.future_use_18
,fs.future_use_19
,fs.future_use_20
,fs.future_use_21
,fs.future_use_22
,fs.future_use_23
,fs.future_use_24
,fs.future_use_25
,fs.future_use_26
,fs.future_use_27
,fs.future_use_28
,fs.future_use_29
,fs.future_use_30
,fs.future_use_31
,fs.future_use_32
,fs.future_use_33
,fs.future_use_34
,fs.future_use_35
,fs.future_use_36
,fs.future_use_37
,fs.future_use_38
,fs.future_use_39
,fs.future_use_40
,fs.future_use_41
,fs.future_use_42
,fs.future_use_43
,fs.future_use_44
,fs.future_use_45
,fs.future_use_46
,fs.future_use_47
,fs.future_use_48
,fs.future_use_49
,fs.future_use_50
,fs.future_use_51
,fs.future_use_52
,fs.future_use_53
,fs.future_use_54
,fs.future_use_55
,fs.future_use_56
,fs.future_use_57
,fs.src_system_id
,fs.src_name
,'fin_tne_mtd_etl_scripts~fin_con_fact'
,'fin_tne_mtd_etl_scripts~fin_con_fact'
,current_timestamp  
,current_timestamp 
from
al_finance.fin_tne_attendee_dtl_fs fs;
