--STEP 1

DELETE FROM AL_FINANCE.FIN_TNE_HOTEL_RESERVATION_F fact 
	using (select * from AL_FINANCE.FIN_TNE_HOTEL_RESERVATION_FS STAGE where STAGE.delete_record = '0') stage
	where fact.src_system_id=stage.SRC_SYSTEM_ID;
--STEP 2

INSERT INTO AL_FINANCE.FIN_TNE_HOTEL_RESERVATION_F
(
	 emp_id
	,base_reportng_cd
	,base_reportng_name
	,org_id
	,org_name
	,issuing_cntry_name
	,traveler_name
	,super_chain_name
	,hotel_chain_cd
	,hotel_chain_name
	,property_name
	,street_address
	,hotel_city
	,hotel_state
	,hotel_zip
	,hotel_cntry
	,hotel_phone_nbr
	,invoice_referral
	,invoice_voucher_nbr
	,obt_action_cd
	,obt_vendor_cd
	,obt_vendor_name
	,obt_vendor_type_name
	,agent_assist_rc
	,booking_method
	,booking_dt
	,issue_dt
	,confirmation_nbr
	,in_dt
	,out_dt
	,metro_city_cd
	,near_metro_city_name
	,near_airport_cd
	,near_airport_name
	,region
	,hotel_only
	,room_type
	,rate_type
	,rate_duration
	,room_rt
	,multiplier_rt
	,nbr_of_rooms
	,room_nights
	,total_hotel_cost
	,supplemental_charges_amt
	,tot_hotel_charges_amt
	,ref_rt
	,ref_cost
	,realized_savings_amt
	,realized_savings_percent
	,lowest_rt
	,low_cost
	,missed_savings_amt
	,missed_saving_percent
	,potential_saivings_amt
	,potential_savings_percent
	,local_curncy_cd
	,local_curncy_rt
	,rc_missed_local_cd
	,rc_missed_local_desc
	,rc_realized_local_cd
	,rc_realized_local_desc
	,rc_missed_global_cd
	,rc_missed_global_desc
	,rc_realized_global_cd
	,rc_realized_global_desc
	,trip_type
	,branch_id
	,agent_id
	,booking_iata_nbr
	,back_office_txn_id
	,harp_cd
	,original_hotel_key
	,pnr
	,gds
	,travel_purpose
	,accnt_nbr
	,pos_fee_amt
	,hier_1
	,hier_2
	,hier_3
	,hier_4
	,hier_5
	,client_defined_1
	,client_defined_2
	,client_defined_3
	,client_defined_4
	,client_defined_5
	,client_defined_6
	,client_defined_7
	,client_defined_8
	,client_defined_9
	,client_defined_10
	,client_defined_11
	,client_defined_12
	,client_defined_13
	,client_defined_14
	,client_defined_15
	,client_defined_16
	,client_defined_17
	,client_defined_18
	,client_defined_19
	,client_defined_20
	,hotel_preferd_compliance
	,src_last_upd_dt
	,delete_record
	,src_system_cd
	,src_system_id
	,src_name
	,dl_ins_by
	,dl_upd_by
	,dl_ins_ts
	,dl_upd_ts
	,business_segment,
	sub_business,
	emp_org,
	sso_id,
	workday_user_name,
	emp_full_name,
	email_address,
	emp_cntry,
	job_family_grp,
	job_family,
	job_name,
	business_grp_name,
	emp_func,
	emp_home_regn,
	operatng_ledger_buc,
	operatng_ledger_cc_cd,
	operatng_ledger_compny_cd,
	operatng_ledger_pl_cd,
	office_address,
	band_grp,
	supervisor_id_lvl_01,
	supervisor_name_lvl_01,
	supervisor_id_lvl_02,
	supervisor_name_lvl_02,
	supervisor_id_lvl_03,
	supervisor_name_lvl_03,
	supervisor_id_lvl_04,
	supervisor_name_lvl_04,
	supervisor_id_lvl_05,
	supervisor_name_lvl_05,
	supervisor_id_lvl_06,
	supervisor_name_lvl_06,
	supervisor_id_lvl_07,
	supervisor_name_lvl_07,
	supervisor_id_lvl_08,
	supervisor_name_lvl_08,
	supervisor_id_lvl_09,
	supervisor_name_lvl_09,
	supervisor_id_lvl_10,
	supervisor_name_lvl_10
	)
SELECT 
	 t.emp_id
	,t.base_reportng_cd
	,t.base_reportng_name
	,t.org_id
	,t.org_name
	,t.issuing_cntry_name
	,t.traveler_name
	,t.super_chain_name
	,t.hotel_chain_cd
	,t.hotel_chain_name
	,t.property_name
	,t.street_address
	,t.hotel_city
	,t.hotel_state
	,t.hotel_zip
	,t.hotel_cntry
	,t.hotel_phone_nbr
	,t.invoice_referral
	,t.invoice_voucher_nbr
	,t.obt_action_cd
	,t.obt_vendor_cd
	,t.obt_vendor_name
	,t.obt_vendor_type_name
	,t.agent_assist_rc
	,t.booking_method
	,t.booking_dt
	,t.issue_dt
	,t.confirmation_nbr
	,t.in_dt
	,t.out_dt
	,t.metro_city_cd
	,t.near_metro_city_name
	,t.near_airport_cd
	,t.near_airport_name
	,t.region
	,t.hotel_only
	,t.room_type
	,t.rate_type
	,t.rate_duration
	,t.room_rt
	,t.multiplier_rt
	,t.nbr_of_rooms
	,t.room_nights
	,t.total_hotel_cost
	,t.supplemental_charges_amt
	,t.tot_hotel_charges_amt
	,t.ref_rt
	,t.ref_cost
	,t.realized_savings_amt
	,t.realized_savings_percent
	,t.lowest_rt
	,t.low_cost
	,t.missed_savings_amt
	,t.missed_saving_percent
	,t.potential_saivings_amt
	,t.potential_savings_percent
	,t.local_curncy_cd
	,t.local_curncy_rt
	,t.rc_missed_local_cd
	,t.rc_missed_local_desc
	,t.rc_realized_local_cd
	,t.rc_realized_local_desc
	,t.rc_missed_global_cd
	,t.rc_missed_global_desc
	,t.rc_realized_global_cd
	,t.rc_realized_global_desc
	,t.trip_type
	,t.branch_id
	,t.agent_id
	,t.booking_iata_nbr
	,t.back_office_txn_id
	,t.harp_cd
	,t.original_hotel_key
	,t.pnr
	,t.gds
	,t.travel_purpose
	,t.accnt_nbr
	,t.pos_fee_amt
	,t.hier_1
	,t.hier_2
	,t.hier_3
	,t.hier_4
	,t.hier_5
	,t.client_defined_1
	,t.client_defined_2
	,t.client_defined_3
	,t.client_defined_4
	,t.client_defined_5
	,t.client_defined_6
	,t.client_defined_7
	,t.client_defined_8
	,t.client_defined_9
	,t.client_defined_10
	,t.client_defined_11
	,t.client_defined_12
	,t.client_defined_13
	,t.client_defined_14
	,t.client_defined_15
	,t.client_defined_16
	,t.client_defined_17
	,t.client_defined_18
	,t.client_defined_19
	,t.client_defined_20
	,t.hotel_preferd_compliance
	,t.src_last_upd_dt
	,t.delete_record
	,t.src_system_cd
	,t.src_system_id
	,t.src_name
	,'fin_tne_mtd_etl_scripts~tne_cwt_fact'
	,'fin_tne_mtd_etl_scripts~tne_cwt_fact'
	,current_timestamp
	,current_timestamp 
	,emp.business_segment AS business_segment,
	emp.sub_business as sub_business,
	emp.assignment_attrib_10 AS emp_org,
	emp.sso_id as SSO_ID,
	emp.workday_user_name,
	emp.emp_full_name,
	emp.email_address as email_address,
	emp.cntry_cd AS emp_cntry,
	emp.job_family_grp as job_family_grp,
	emp.job_family,
	emp.job_name,
	emp.business_grp_name,
	emp.emp_func,
	emp.emp_home_regn as emp_home_regn,
	emp.operatng_ledger_buc,
	emp.operatng_ledger_cc_cd as operatng_ledger_cc_cd,
	emp.operatng_ledger_compny_cd as operatng_ledger_compny_cd,
	emp.operatng_ledger_pl_cd,
	emp.office_address,
	emp.band_grp,
	emp.supervisor_id_lvl_01,
	emp.supervisor_name_lvl_01,
	emp.supervisor_id_lvl_02,
	emp.supervisor_name_lvl_02,
	emp.supervisor_id_lvl_03,
	emp.supervisor_name_lvl_03,
	emp.supervisor_id_lvl_04,
	emp.supervisor_name_lvl_04,
	emp.supervisor_id_lvl_05,
	emp.supervisor_name_lvl_05,
	emp.supervisor_id_lvl_06,
	emp.supervisor_name_lvl_06,
	emp.supervisor_id_lvl_07,
	emp.supervisor_name_lvl_07,
	emp.supervisor_id_lvl_08,
	emp.supervisor_name_lvl_08,
	emp.supervisor_id_lvl_09,
	emp.supervisor_name_lvl_09,
	emp.supervisor_id_lvl_10,
	emp.supervisor_name_lvl_10
FROM 
 (select a.* ,row_number() over (partition by src_system_id order by src_last_upd_dt Desc) as rn FROM
	AL_FINANCE.FIN_TNE_HOTEL_RESERVATION_FS a  where a.delete_record ='0') t 
LEFT JOIN al_finance.fin_employee_d emp ON t.emp_id = emp.src_system_id
WHERE t.rn=1
AND delete_record ='0';
--STEP 3

CREATE TEMP TABLE TEMP_HOTEL_RESERVATIONS
 AS (SELECT fs_deleted.* FROM (SELECT t.*,row_number() over(partition by src_system_id order by src_system_id) as rn 
					from AL_FINANCE.FIN_TNE_HOTEL_RESERVATION_FS t  where delete_record = '1') fs_deleted WHERE fs_deleted.rn = 1) DISTRIBUTED BY (src_system_id);
--STEP 4

UPDATE AL_FINANCE.FIN_TNE_HOTEL_RESERVATION_F F
SET delete_record = '1'
FROM TEMP_HOTEL_RESERVATIONS fs_temp
WHERE fs_temp.src_system_id = f.src_system_id;
--STEP 5

INSERT INTO AL_FINANCE.FIN_TNE_HOTEL_RESERVATION_F
(
	 emp_id
	,base_reportng_cd
	,base_reportng_name
	,org_id
	,org_name
	,issuing_cntry_name
	,traveler_name
	,super_chain_name
	,hotel_chain_cd
	,hotel_chain_name
	,property_name
	,street_address
	,hotel_city
	,hotel_state
	,hotel_zip
	,hotel_cntry
	,hotel_phone_nbr
	,invoice_referral
	,invoice_voucher_nbr
	,obt_action_cd
	,obt_vendor_cd
	,obt_vendor_name
	,obt_vendor_type_name
	,agent_assist_rc
	,booking_method
	,booking_dt
	,issue_dt
	,confirmation_nbr
	,in_dt
	,out_dt
	,metro_city_cd
	,near_metro_city_name
	,near_airport_cd
	,near_airport_name
	,region
	,hotel_only
	,room_type
	,rate_type
	,rate_duration
	,room_rt
	,multiplier_rt
	,nbr_of_rooms
	,room_nights
	,total_hotel_cost
	,supplemental_charges_amt
	,tot_hotel_charges_amt
	,ref_rt
	,ref_cost
	,realized_savings_amt
	,realized_savings_percent
	,lowest_rt
	,low_cost
	,missed_savings_amt
	,missed_saving_percent
	,potential_saivings_amt
	,potential_savings_percent
	,local_curncy_cd
	,local_curncy_rt
	,rc_missed_local_cd
	,rc_missed_local_desc
	,rc_realized_local_cd
	,rc_realized_local_desc
	,rc_missed_global_cd
	,rc_missed_global_desc
	,rc_realized_global_cd
	,rc_realized_global_desc
	,trip_type
	,branch_id
	,agent_id
	,booking_iata_nbr
	,back_office_txn_id
	,harp_cd
	,original_hotel_key
	,pnr
	,gds
	,travel_purpose
	,accnt_nbr
	,pos_fee_amt
	,hier_1
	,hier_2
	,hier_3
	,hier_4
	,hier_5
	,client_defined_1
	,client_defined_2
	,client_defined_3
	,client_defined_4
	,client_defined_5
	,client_defined_6
	,client_defined_7
	,client_defined_8
	,client_defined_9
	,client_defined_10
	,client_defined_11
	,client_defined_12
	,client_defined_13
	,client_defined_14
	,client_defined_15
	,client_defined_16
	,client_defined_17
	,client_defined_18
	,client_defined_19
	,client_defined_20
	,hotel_preferd_compliance
	,src_last_upd_dt
	,delete_record
	,src_system_cd
	,src_system_id
	,src_name
	,dl_ins_by
	,dl_upd_by
	,dl_ins_ts
	,dl_upd_ts
	,business_segment,
	sub_business,
	emp_org,
	sso_id,
	workday_user_name,
	emp_full_name,
	email_address,
	emp_cntry,
	job_family_grp,
	job_family,
	job_name,
	business_grp_name,
	emp_func,
	emp_home_regn,
	operatng_ledger_buc,
	operatng_ledger_cc_cd,
	operatng_ledger_compny_cd,
	operatng_ledger_pl_cd,
	office_address,
	band_grp,
	supervisor_id_lvl_01,
	supervisor_name_lvl_01,
	supervisor_id_lvl_02,
	supervisor_name_lvl_02,
	supervisor_id_lvl_03,
	supervisor_name_lvl_03,
	supervisor_id_lvl_04,
	supervisor_name_lvl_04,
	supervisor_id_lvl_05,
	supervisor_name_lvl_05,
	supervisor_id_lvl_06,
	supervisor_name_lvl_06,
	supervisor_id_lvl_07,
	supervisor_name_lvl_07,
	supervisor_id_lvl_08,
	supervisor_name_lvl_08,
	supervisor_id_lvl_09,
	supervisor_name_lvl_09,
	supervisor_id_lvl_10,
	supervisor_name_lvl_10
)
SELECT 
	 TEMP.emp_id
	,TEMP.base_reportng_cd
	,TEMP.base_reportng_name
	,TEMP.org_id
	,TEMP.org_name
	,TEMP.issuing_cntry_name
	,TEMP.traveler_name
	,TEMP.super_chain_name
	,TEMP.hotel_chain_cd
	,TEMP.hotel_chain_name
	,TEMP.property_name
	,TEMP.street_address
	,TEMP.hotel_city
	,TEMP.hotel_state
	,TEMP.hotel_zip
	,TEMP.hotel_cntry
	,TEMP.hotel_phone_nbr
	,TEMP.invoice_referral
	,TEMP.invoice_voucher_nbr
	,TEMP.obt_action_cd
	,TEMP.obt_vendor_cd
	,TEMP.obt_vendor_name
	,TEMP.obt_vendor_type_name
	,TEMP.agent_assist_rc
	,TEMP.booking_method
	,TEMP.booking_dt
	,TEMP.issue_dt
	,TEMP.confirmation_nbr
	,TEMP.in_dt
	,TEMP.out_dt
	,TEMP.metro_city_cd
	,TEMP.near_metro_city_name
	,TEMP.near_airport_cd
	,TEMP.near_airport_name
	,TEMP.region
	,TEMP.hotel_only
	,TEMP.room_type
	,TEMP.rate_type
	,TEMP.rate_duration
	,TEMP.room_rt
	,TEMP.multiplier_rt
	,TEMP.nbr_of_rooms
	,TEMP.room_nights
	,TEMP.total_hotel_cost
	,TEMP.supplemental_charges_amt
	,TEMP.tot_hotel_charges_amt
	,TEMP.ref_rt
	,TEMP.ref_cost
	,TEMP.realized_savings_amt
	,TEMP.realized_savings_percent
	,TEMP.lowest_rt
	,TEMP.low_cost
	,TEMP.missed_savings_amt
	,TEMP.missed_saving_percent
	,TEMP.potential_saivings_amt
	,TEMP.potential_savings_percent
	,TEMP.local_curncy_cd
	,TEMP.local_curncy_rt
	,TEMP.rc_missed_local_cd
	,TEMP.rc_missed_local_desc
	,TEMP.rc_realized_local_cd
	,TEMP.rc_realized_local_desc
	,TEMP.rc_missed_global_cd
	,TEMP.rc_missed_global_desc
	,TEMP.rc_realized_global_cd
	,TEMP.rc_realized_global_desc
	,TEMP.trip_type
	,TEMP.branch_id
	,TEMP.agent_id
	,TEMP.booking_iata_nbr
	,TEMP.back_office_txn_id
	,TEMP.harp_cd
	,TEMP.original_hotel_key
	,TEMP.pnr
	,TEMP.gds
	,TEMP.travel_purpose
	,TEMP.accnt_nbr
	,TEMP.pos_fee_amt
	,TEMP.hier_1
	,TEMP.hier_2
	,TEMP.hier_3
	,TEMP.hier_4
	,TEMP.hier_5
	,TEMP.client_defined_1
	,TEMP.client_defined_2
	,TEMP.client_defined_3
	,TEMP.client_defined_4
	,TEMP.client_defined_5
	,TEMP.client_defined_6
	,TEMP.client_defined_7
	,TEMP.client_defined_8
	,TEMP.client_defined_9
	,TEMP.client_defined_10
	,TEMP.client_defined_11
	,TEMP.client_defined_12
	,TEMP.client_defined_13
	,TEMP.client_defined_14
	,TEMP.client_defined_15
	,TEMP.client_defined_16
	,TEMP.client_defined_17
	,TEMP.client_defined_18
	,TEMP.client_defined_19
	,TEMP.client_defined_20
	,TEMP.hotel_preferd_compliance
	,TEMP.src_last_upd_dt
	,TEMP.delete_record
	,TEMP.src_system_cd
	,TEMP.src_system_id
	,TEMP.src_name
	,'fin_tne_mtd_etl_scripts~tne_cwt_fact'
	,'fin_tne_mtd_etl_scripts~tne_cwt_fact'
	,current_timestamp
	,current_timestamp 
	,emp.business_segment AS business_segment,
	emp.sub_business as sub_business,
	emp.assignment_attrib_10 AS emp_org,
	emp.sso_id as SSO_ID,
	emp.workday_user_name,
	emp.emp_full_name,
	emp.email_address as email_address,
	emp.cntry_cd AS emp_cntry,
	emp.job_family_grp as job_family_grp,
	emp.job_family,
	emp.job_name,
	emp.business_grp_name,
	emp.emp_func,
	emp.emp_home_regn as emp_home_regn,
	emp.operatng_ledger_buc,
	emp.operatng_ledger_cc_cd as operatng_ledger_cc_cd,
	emp.operatng_ledger_compny_cd as operatng_ledger_compny_cd,
	emp.operatng_ledger_pl_cd,
	emp.office_address,
	emp.band_grp,
	emp.supervisor_id_lvl_01,
	emp.supervisor_name_lvl_01,
	emp.supervisor_id_lvl_02,
	emp.supervisor_name_lvl_02,
	emp.supervisor_id_lvl_03,
	emp.supervisor_name_lvl_03,
	emp.supervisor_id_lvl_04,
	emp.supervisor_name_lvl_04,
	emp.supervisor_id_lvl_05,
	emp.supervisor_name_lvl_05,
	emp.supervisor_id_lvl_06,
	emp.supervisor_name_lvl_06,
	emp.supervisor_id_lvl_07,
	emp.supervisor_name_lvl_07,
	emp.supervisor_id_lvl_08,
	emp.supervisor_name_lvl_08,
	emp.supervisor_id_lvl_09,
	emp.supervisor_name_lvl_09,
	emp.supervisor_id_lvl_10,
	emp.supervisor_name_lvl_10
FROM
TEMP_HOTEL_RESERVATIONS temp
LEFT JOIN al_finance.fin_employee_d emp ON temp.emp_id = emp.src_system_id
LEFT JOIN AL_FINANCE.FIN_TNE_HOTEL_RESERVATION_F f ON temp.src_system_id = f.src_system_id
WHERE
f.src_system_id is null;
