--STEP 1

DELETE FROM AL_FINANCE.FIN_TNE_CAR_RESERVATION_F fact 
	using (select * from AL_FINANCE.FIN_TNE_CAR_RESERVATION_FS STAGE where STAGE.delete_record = '0') stage
	where fact.src_system_id=stage.SRC_SYSTEM_ID;
--STEP 2

INSERT INTO AL_FINANCE.FIN_TNE_CAR_RESERVATION_F
(
	emp_id
	,base_reportng_cd
	,issuing_cntry_name
	,traveler_name
	,car_supplier_cd
	,car_supplier_name
	,obt_action_cd
	,obt_vendor_cd
	,agent_assist_rc
	,booking_dt
	,issue_dt
	,confirmation_nbr
	,invoice_voucher_nbr
	,pick_up_city_cd
	,pick_up_city_name
	,pick_up_cntry_name
	,pick_up_regn_name
	,drop_off_city_cd
	,drop_off_city_name
	,drop_off_cntry_name
	,drop_off_regn_name
	,pick_up_dt
	,pick_up_time
	,drop_off_dt
	,drop_off_time
	,car_only
	,car_type
	,rate_duration
	,rental_rt
	,rate_multiplier
	,nbr_of_cars
	,car_days
	,total_car_cost
	,lowest_rate
	,ref_rate
	,local_curncy_cd
	,local_curncy_rt
	,invoice_referral
	,rc_missed_local_cd
	,rc_missed_local_desc
	,rc_realized_local_cd
	,rc_realized_local_desc
	,rc_missed_global_cd
	,rc_missed_global_desc
	,rc_realized_global_cd
	,rc_realized_global_desc
	,trip_type
	,branch_id
	,agent_id
	,booking_iata_nbr
	,back_office_txn_id
	,pnr
	,gds
	,travel_purpose
	,accnt_nbr
	,pos_fee_amt
	,hier_1
	,hier_2
	,hier_3
	,hier_4
	,hier_5
	,client_defined_1
	,client_defined_2
	,client_defined_3
	,client_defined_4
	,client_defined_5
	,client_defined_6
	,client_defined_7
	,client_defined_8
	,client_defined_9
	,client_defined_10
	,client_defined_11
	,client_defined_12
	,client_defined_13
	,client_defined_14
	,client_defined_15
	,client_defined_16
	,client_defined_17
	,client_defined_18
	,client_defined_19
	,client_defined_20
	,src_last_upd_dt
	,delete_record
	,src_system_cd
	,src_system_id
	,src_name
	,dl_ins_by
	,dl_upd_by
	,dl_ins_ts
	,dl_upd_ts
	,business_segment,
	sub_business,
	emp_org,
	sso_id,
	workday_user_name,
	emp_full_name,
	email_address,
	emp_cntry,
	job_family_grp,
	job_family,
	job_name,
	business_grp_name,
	emp_func,
	emp_home_regn,
	operatng_ledger_buc,
	operatng_ledger_cc_cd,
	operatng_ledger_compny_cd,
	operatng_ledger_pl_cd,
	office_address,
	band_grp,
	supervisor_id_lvl_01,
	supervisor_name_lvl_01,
	supervisor_id_lvl_02,
	supervisor_name_lvl_02,
	supervisor_id_lvl_03,
	supervisor_name_lvl_03,
	supervisor_id_lvl_04,
	supervisor_name_lvl_04,
	supervisor_id_lvl_05,
	supervisor_name_lvl_05,
	supervisor_id_lvl_06,
	supervisor_name_lvl_06,
	supervisor_id_lvl_07,
	supervisor_name_lvl_07,
	supervisor_id_lvl_08,
	supervisor_name_lvl_08,
	supervisor_id_lvl_09,
	supervisor_name_lvl_09,
	supervisor_id_lvl_10,
	supervisor_name_lvl_10	
	)
SELECT 
	 t.emp_id
	,t.base_reportng_cd
	,t.issuing_cntry_name
	,t.traveler_name
	,t.car_supplier_cd
	,t.car_supplier_name
	,t.obt_action_cd
	,t.obt_vendor_cd
	,t.agent_assist_rc
	,t.booking_dt
	,t.issue_dt
	,t.confirmation_nbr
	,t.invoice_voucher_nbr
	,t.pick_up_city_cd
	,t.pick_up_city_name
	,t.pick_up_cntry_name
	,t.pick_up_regn_name
	,t.drop_off_city_cd
	,t.drop_off_city_name
	,t.drop_off_cntry_name
	,t.drop_off_regn_name
	,t.pick_up_dt
	,t.pick_up_time
	,t.drop_off_dt
	,t.drop_off_time
	,t.car_only
	,t.car_type
	,t.rate_duration
	,t.rental_rt
	,t.rate_multiplier
	,t.nbr_of_cars
	,t.car_days
	,t.total_car_cost
	,t.lowest_rate
	,t.ref_rate
	,t.local_curncy_cd
	,t.local_curncy_rt
	,t.invoice_referral
	,t.rc_missed_local_cd
	,t.rc_missed_local_desc
	,t.rc_realized_local_cd
	,t.rc_realized_local_desc
	,t.rc_missed_global_cd
	,t.rc_missed_global_desc
	,t.rc_realized_global_cd
	,t.rc_realized_global_desc
	,t.trip_type
	,t.branch_id
	,t.agent_id
	,t.booking_iata_nbr
	,t.back_office_txn_id
	,t.pnr
	,t.gds
	,t.travel_purpose
	,t.accnt_nbr
	,t.pos_fee_amt
	,t.hier_1
	,t.hier_2
	,t.hier_3
	,t.hier_4
	,t.hier_5
	,t.client_defined_1
	,t.client_defined_2
	,t.client_defined_3
	,t.client_defined_4
	,t.client_defined_5
	,t.client_defined_6
	,t.client_defined_7
	,t.client_defined_8
	,t.client_defined_9
	,t.client_defined_10
	,t.client_defined_11
	,t.client_defined_12
	,t.client_defined_13
	,t.client_defined_14
	,t.client_defined_15
	,t.client_defined_16
	,t.client_defined_17
	,t.client_defined_18
	,t.client_defined_19
	,t.client_defined_20
	,t.src_last_upd_dt
	,t.delete_record
	,t.src_system_cd
	,t.src_system_id
	,t.src_name
	,'fin_tne_mtd_etl_scripts~tne_cwt_fact'
	,'fin_tne_mtd_etl_scripts~tne_cwt_fact'
	,current_timestamp
	,current_timestamp 
	,emp.business_segment AS business_segment,
	emp.sub_business as sub_business,
	emp.assignment_attrib_10 AS emp_org,
	emp.sso_id as SSO_ID,
	emp.workday_user_name,
	emp.emp_full_name,
	emp.email_address as email_address,
	emp.cntry_cd AS emp_cntry,
	emp.job_family_grp as job_family_grp,
	emp.job_family,
	emp.job_name,
	emp.business_grp_name,
	emp.emp_func,
	emp.emp_home_regn as emp_home_regn,
	emp.operatng_ledger_buc,
	emp.operatng_ledger_cc_cd as operatng_ledger_cc_cd,
	emp.operatng_ledger_compny_cd as operatng_ledger_compny_cd,
	emp.operatng_ledger_pl_cd,
	emp.office_address,
	emp.band_grp,
	emp.supervisor_id_lvl_01,
	emp.supervisor_name_lvl_01,
	emp.supervisor_id_lvl_02,
	emp.supervisor_name_lvl_02,
	emp.supervisor_id_lvl_03,
	emp.supervisor_name_lvl_03,
	emp.supervisor_id_lvl_04,
	emp.supervisor_name_lvl_04,
	emp.supervisor_id_lvl_05,
	emp.supervisor_name_lvl_05,
	emp.supervisor_id_lvl_06,
	emp.supervisor_name_lvl_06,
	emp.supervisor_id_lvl_07,
	emp.supervisor_name_lvl_07,
	emp.supervisor_id_lvl_08,
	emp.supervisor_name_lvl_08,
	emp.supervisor_id_lvl_09,
	emp.supervisor_name_lvl_09,
	emp.supervisor_id_lvl_10,
	emp.supervisor_name_lvl_10	
FROM 
(select a.* ,row_number() over (partition by src_system_id order by src_last_upd_dt DESC) as rn FROM
AL_FINANCE.FIN_TNE_CAR_RESERVATION_FS a WHERE a.delete_record = '0' ) t 
LEFT JOIN al_finance.fin_employee_d emp ON t.emp_id = emp.src_system_id
WHERE t.rn=1
AND delete_record = '0';
--STEP 3

CREATE TEMP TABLE TEMP_CAR_RESERVATIONS
 AS (SELECT fs_deleted.* FROM (SELECT t.*,row_number() over(partition by src_system_id order by src_system_id) as rn 
					from AL_FINANCE.FIN_TNE_CAR_RESERVATION_FS t  where delete_record = '1') fs_deleted WHERE fs_deleted.rn = 1) DISTRIBUTED BY (src_system_id);
--STEP 4

UPDATE AL_FINANCE.FIN_TNE_CAR_RESERVATION_F F
SET delete_record = '1'
FROM TEMP_CAR_RESERVATIONS fs_temp
WHERE fs_temp.src_system_id = f.src_system_id;
--STEP 5

INSERT INTO AL_FINANCE.FIN_TNE_CAR_RESERVATION_F
(
	 emp_id
	,base_reportng_cd
	,issuing_cntry_name
	,traveler_name
	,car_supplier_cd
	,car_supplier_name
	,obt_action_cd
	,obt_vendor_cd
	,agent_assist_rc
	,booking_dt
	,issue_dt
	,confirmation_nbr
	,invoice_voucher_nbr
	,pick_up_city_cd
	,pick_up_city_name
	,pick_up_cntry_name
	,pick_up_regn_name
	,drop_off_city_cd
	,drop_off_city_name
	,drop_off_cntry_name
	,drop_off_regn_name
	,pick_up_dt
	,pick_up_time
	,drop_off_dt
	,drop_off_time
	,car_only
	,car_type
	,rate_duration
	,rental_rt
	,rate_multiplier
	,nbr_of_cars
	,car_days
	,total_car_cost
	,lowest_rate
	,ref_rate
	,local_curncy_cd
	,local_curncy_rt
	,invoice_referral
	,rc_missed_local_cd
	,rc_missed_local_desc
	,rc_realized_local_cd
	,rc_realized_local_desc
	,rc_missed_global_cd
	,rc_missed_global_desc
	,rc_realized_global_cd
	,rc_realized_global_desc
	,trip_type
	,branch_id
	,agent_id
	,booking_iata_nbr
	,back_office_txn_id
	,pnr
	,gds
	,travel_purpose
	,accnt_nbr
	,pos_fee_amt
	,hier_1
	,hier_2
	,hier_3
	,hier_4
	,hier_5
	,client_defined_1
	,client_defined_2
	,client_defined_3
	,client_defined_4
	,client_defined_5
	,client_defined_6
	,client_defined_7
	,client_defined_8
	,client_defined_9
	,client_defined_10
	,client_defined_11
	,client_defined_12
	,client_defined_13
	,client_defined_14
	,client_defined_15
	,client_defined_16
	,client_defined_17
	,client_defined_18
	,client_defined_19
	,client_defined_20
	,src_last_upd_dt
	,delete_record
	,src_system_cd
	,src_system_id
	,src_name
	,dl_ins_by
	,dl_upd_by
	,dl_ins_ts
	,dl_upd_ts
	,business_segment,
	sub_business,
	emp_org,
	sso_id,
	workday_user_name,
	emp_full_name,
	email_address,
	emp_cntry,
	job_family_grp,
	job_family,
	job_name,
	business_grp_name,
	emp_func,
	emp_home_regn,
	operatng_ledger_buc,
	operatng_ledger_cc_cd,
	operatng_ledger_compny_cd,
	operatng_ledger_pl_cd,
	office_address,
	band_grp,
	supervisor_id_lvl_01,
	supervisor_name_lvl_01,
	supervisor_id_lvl_02,
	supervisor_name_lvl_02,
	supervisor_id_lvl_03,
	supervisor_name_lvl_03,
	supervisor_id_lvl_04,
	supervisor_name_lvl_04,
	supervisor_id_lvl_05,
	supervisor_name_lvl_05,
	supervisor_id_lvl_06,
	supervisor_name_lvl_06,
	supervisor_id_lvl_07,
	supervisor_name_lvl_07,
	supervisor_id_lvl_08,
	supervisor_name_lvl_08,
	supervisor_id_lvl_09,
	supervisor_name_lvl_09,
	supervisor_id_lvl_10,
	supervisor_name_lvl_10	
)
SELECT 
	 temp.emp_id
	,temp.base_reportng_cd
	,temp.issuing_cntry_name
	,temp.traveler_name
	,temp.car_supplier_cd
	,temp.car_supplier_name
	,temp.obt_action_cd
	,temp.obt_vendor_cd
	,temp.agent_assist_rc
	,temp.booking_dt
	,temp.issue_dt
	,temp.confirmation_nbr
	,temp.invoice_voucher_nbr
	,temp.pick_up_city_cd
	,temp.pick_up_city_name
	,temp.pick_up_cntry_name
	,temp.pick_up_regn_name
	,temp.drop_off_city_cd
	,temp.drop_off_city_name
	,temp.drop_off_cntry_name
	,temp.drop_off_regn_name
	,temp.pick_up_dt
	,temp.pick_up_time
	,temp.drop_off_dt
	,temp.drop_off_time
	,temp.car_only
	,temp.car_type
	,temp.rate_duration
	,temp.rental_rt
	,temp.rate_multiplier
	,temp.nbr_of_cars
	,temp.car_days
	,temp.total_car_cost
	,temp.lowest_rate
	,temp.ref_rate
	,temp.local_curncy_cd
	,temp.local_curncy_rt
	,temp.invoice_referral
	,temp.rc_missed_local_cd
	,temp.rc_missed_local_desc
	,temp.rc_realized_local_cd
	,temp.rc_realized_local_desc
	,temp.rc_missed_global_cd
	,temp.rc_missed_global_desc
	,temp.rc_realized_global_cd
	,temp.rc_realized_global_desc
	,temp.trip_type
	,temp.branch_id
	,temp.agent_id
	,temp.booking_iata_nbr
	,temp.back_office_txn_id
	,temp.pnr
	,temp.gds
	,temp.travel_purpose
	,temp.accnt_nbr
	,temp.pos_fee_amt
	,temp.hier_1
	,temp.hier_2
	,temp.hier_3
	,temp.hier_4
	,temp.hier_5
	,temp.client_defined_1
	,temp.client_defined_2
	,temp.client_defined_3
	,temp.client_defined_4
	,temp.client_defined_5
	,temp.client_defined_6
	,temp.client_defined_7
	,temp.client_defined_8
	,temp.client_defined_9
	,temp.client_defined_10
	,temp.client_defined_11
	,temp.client_defined_12
	,temp.client_defined_13
	,temp.client_defined_14
	,temp.client_defined_15
	,temp.client_defined_16
	,temp.client_defined_17
	,temp.client_defined_18
	,temp.client_defined_19
	,temp.client_defined_20
	,temp.src_last_upd_dt
	,temp.delete_record
	,temp.src_system_cd
	,temp.src_system_id
	,temp.src_name
	,'fin_tne_mtd_etl_scripts~tne_cwt_fact'
	,'fin_tne_mtd_etl_scripts~tne_cwt_fact'
	,current_timestamp
	,current_timestamp 
	,emp.business_segment AS business_segment,
	emp.sub_business as sub_business,
	emp.assignment_attrib_10 AS emp_org,
	emp.sso_id as SSO_ID,
	emp.workday_user_name,
	emp.emp_full_name,
	emp.email_address as email_address,
	emp.cntry_cd AS emp_cntry,
	emp.job_family_grp as job_family_grp,
	emp.job_family,
	emp.job_name,
	emp.business_grp_name,
	emp.emp_func,
	emp.emp_home_regn as emp_home_regn,
	emp.operatng_ledger_buc,
	emp.operatng_ledger_cc_cd as operatng_ledger_cc_cd,
	emp.operatng_ledger_compny_cd as operatng_ledger_compny_cd,
	emp.operatng_ledger_pl_cd,
	emp.office_address,
	emp.band_grp,
	emp.supervisor_id_lvl_01,
	emp.supervisor_name_lvl_01,
	emp.supervisor_id_lvl_02,
	emp.supervisor_name_lvl_02,
	emp.supervisor_id_lvl_03,
	emp.supervisor_name_lvl_03,
	emp.supervisor_id_lvl_04,
	emp.supervisor_name_lvl_04,
	emp.supervisor_id_lvl_05,
	emp.supervisor_name_lvl_05,
	emp.supervisor_id_lvl_06,
	emp.supervisor_name_lvl_06,
	emp.supervisor_id_lvl_07,
	emp.supervisor_name_lvl_07,
	emp.supervisor_id_lvl_08,
	emp.supervisor_name_lvl_08,
	emp.supervisor_id_lvl_09,
	emp.supervisor_name_lvl_09,
	emp.supervisor_id_lvl_10,
	emp.supervisor_name_lvl_10	
FROM
TEMP_CAR_RESERVATIONS temp
LEFT JOIN al_finance.fin_employee_d emp ON temp.emp_id = emp.src_system_id
LEFT JOIN AL_FINANCE.FIN_TNE_CAR_RESERVATION_F f ON temp.src_system_id = f.src_system_id
WHERE
f.src_system_id is null;
