--STEP 1

TRUNCATE TABLE AL_FINANCE.FIN_TNE_ATTENDEE_DTL_FS;
--STEP 2

Insert into al_finance.FIN_TNE_ATTENDEE_DTL_FS(
 batch_constant
,batch_id
,batch_dt
,batch_seq_nbr
,emp_id
,emp_last_name
,emp_first_name
,emp_mid_name
,emp_custom_21
,emp_org_unit_1
,emp_org_unit_2
,emp_org_unit_3
,emp_org_unit_4
,emp_org_unit_5
,emp_org_unit_6
,future_use_1
,future_use_2
,future_use_3
,rep_id
,rep_key
,ledger_cd
,rep_curncy_alpha_cd
,rep_home_cntry_name
,rep_submit_dt
,rep_user_defined_dt
,rep_proc_payment_dt
,rep_name
,rep_policy_name
,future_use_4
,rep_org_unit_1
,rep_org_unit_2
,rep_org_unit_3
,rep_org_unit_4
,rep_org_unit_5
,rep_org_unit_6
,rep_custom_1
,rep_custom_2
,rep_custom_3
,rep_custom_4
,rep_custom_5
,rep_custom_6
,rep_custom_7
,rep_custom_8
,rep_custom_9
,rep_custom_10
,rep_custom_11
,rep_custom_12
,rep_custom_13
,rep_custom_14
,rep_custom_15
,rep_custom_16
,vendor_id
,rep_custom_18
,rep_custom_19
,rep_custom_20
,rep_entry_id
,rep_entry_txn_type
,rep_entry_expense_type_name
,rep_entry_txn_dt
,rep_entry_curncy_cd
,rep_entry_exchange_rt
,dir_rep_entry_exchange_rt
,rep_entry_personal_flag
,rep_entry_desc
,rep_entry_vendor_name
,rep_entry_vendor_desc
,rep_entry_attendee_cnt
,rep_entry_org_unit_1
,rep_entry_org_unit_2
,rep_entry_org_unit_3
,rep_entry_org_unit_4
,rep_entry_org_unit_5
,rep_entry_org_unit_6
,rep_entry_custom_1
,rep_entry_custom_2
,rep_entry_custom_3
,rep_entry_custom_4
,rep_entry_custom_5
,rep_entry_custom_6
,rep_entry_custom_7
,rep_entry_custom_8
,rep_entry_custom_9
,rep_entry_custom_10
,rep_entry_custom_11
,rep_entry_custom_12
,rep_entry_custom_13
,rep_entry_custom_14
,rep_entry_custom_15
,rep_entry_custom_16
,rep_entry_custom_17
,rep_entry_custom_18
,rep_entry_custom_19
,rep_entry_custom_20
,rep_entry_custom_21
,rep_entry_custom_22
,rep_entry_custom_23
,rep_entry_custom_24
,rep_entry_custom_25
,rep_entry_custom_26
,rep_entry_custom_27
,rep_entry_custom_28
,rep_entry_custom_29
,rep_entry_custom_30
,rep_entry_custom_31
,rep_entry_custom_32
,rep_entry_custom_33
,rep_entry_custom_34
,rep_entry_custom_35
,rep_entry_custom_36
,rep_entry_custom_37
,rep_entry_custom_38
,rep_entry_custom_39
,rep_entry_custom_40
,rep_entry_txn_amt
,rep_entry_posted_amt
,rep_entry_approved_amt
,future_use_5
,attendee_key
,attendee_unique_idn
,attendee_type_name
,attendee_type_cd
,attendee_last_name
,attendee_first_name
,attendee_compny_name
,attendee_title
,attendee_ytd_amt
,attendee_prev_year_amt
,attendee_curncy_alpha_cd
,attendee_custom_1
,attendee_custom_2
,attendee_custom_3
,attendee_custom_4
,attendee_custom_5
,attendee_custom_6
,attendee_custom_7
,attendee_custom_8
,attendee_custom_9
,attendee_custom_10
,attendee_custom_11
,attendee_custom_12
,attendee_custom_13
,attendee_custom_14
,attendee_custom_15
,attendee_custom_16
,attendee_custom_17
,attendee_custom_18
,attendee_custom_19
,attendee_custom_20
,attendee_txn_amt
,reimbcurncy_attendee_apprvd_amt
,curncy_attendee_approved_amt
,attendee_instance_cnt
,attendee_amt_is_edited
,attendee_entry_custom_1
,attendee_entry_custom_2
,attendee_entry_custom_3
,attendee_entry_custom_4
,attendee_entry_custom_5
,attendee_midle_initial
,attendee_suffix
,expense_locatn_cntry_cd
,expense_locatn_state
,expense_locatn_city_name
,attendee_custom_21
,attendee_custom_22
,attendee_custom_23
,attendee_custom_24
,attendee_custom_25
,future_use_6
,future_use_7
,future_use_8
,future_use_9
,future_use_10
,future_use_11
,future_use_12
,future_use_13
,future_use_14
,future_use_15
,future_use_16
,future_use_17
,future_use_18
,future_use_19
,future_use_20
,future_use_21
,future_use_22
,future_use_23
,future_use_24
,future_use_25
,future_use_26
,future_use_27
,future_use_28
,future_use_29
,future_use_30
,future_use_31
,future_use_32
,future_use_33
,future_use_34
,future_use_35
,future_use_36
,future_use_37
,future_use_38
,future_use_39
,future_use_40
,future_use_41
,future_use_42
,future_use_43
,future_use_44
,future_use_45
,future_use_46
,future_use_47
,future_use_48
,future_use_49
,future_use_50
,future_use_51
,future_use_52
,future_use_53
,future_use_54
,future_use_55
,future_use_56
,future_use_57
,src_system_id
,src_name
,dl_ins_by
,dl_upd_by
,dl_ins_ts
,dl_upd_ts)

select  batch_constant
,batch_id
,TO_DATE(batch_dt,'YYYY-MM-DD')
,batch_seq_nbr
,emp_id
,emp_last_name
,emp_first_name
,emp_mid_name
,emp_custom_21
,emp_org_unit_1
,emp_org_unit_2
,emp_org_unit_3
,emp_org_unit_4
,emp_org_unit_5
,emp_org_unit_6
,future_use_1
,future_use_2
,future_use_3
,rep_id
,rep_key
,ledger_cd
,rep_curncy_alpha_cd
,rep_home_cntry_name
,TO_DATE(rep_submit_dt,'YYYY-MM-DD')
,TO_DATE(rep_user_defined_dt,'YYYY-MM-DD')
,TO_DATE(rep_proc_payment_dt,'YYYY-MM-DD')
,rep_name
,rep_policy_name
,future_use_4
,rep_org_unit_1
,rep_org_unit_2
,rep_org_unit_3
,rep_org_unit_4
,rep_org_unit_5
,rep_org_unit_6
,rep_custom_1
,rep_custom_2
,rep_custom_3
,rep_custom_4
,rep_custom_5
,rep_custom_6
,rep_custom_7
,rep_custom_8
,rep_custom_9
,rep_custom_10
,rep_custom_11
,rep_custom_12
,rep_custom_13
,rep_custom_14
,rep_custom_15
,rep_custom_16
,vendor_id
,rep_custom_18
,rep_custom_19
,rep_custom_20
,rep_entry_id
,rep_entry_txn_type
,rep_entry_expense_type_name
,TO_DATE(rep_entry_txn_dt,'YYYY-MM-DD')
,rep_entry_curncy_cd
,CAST(rep_entry_exchange_rt AS NUMERIC)
,dir_rep_entry_exchange_rt
,rep_entry_personal_flag
,rep_entry_desc
,rep_entry_vendor_name
,rep_entry_vendor_desc 
,rep_entry_attendee_cnt
,rep_entry_org_unit_1
,rep_entry_org_unit_2
,rep_entry_org_unit_3
,rep_entry_org_unit_4
,rep_entry_org_unit_5
,rep_entry_org_unit_6
,rep_entry_custom_1
,rep_entry_custom_2
,rep_entry_custom_3
,rep_entry_custom_4
,rep_entry_custom_5
,rep_entry_custom_6
,rep_entry_custom_7
,rep_entry_custom_8
,rep_entry_custom_9
,rep_entry_custom_10
,rep_entry_custom_11
,rep_entry_custom_12
,rep_entry_custom_13
,rep_entry_custom_14
,rep_entry_custom_15
,rep_entry_custom_16
,rep_entry_custom_17
,rep_entry_custom_18
,rep_entry_custom_19
,rep_entry_custom_20
,rep_entry_custom_21
,rep_entry_custom_22
,rep_entry_custom_23
,rep_entry_custom_24
,rep_entry_custom_25
,rep_entry_custom_26
,rep_entry_custom_27
,rep_entry_custom_28
,rep_entry_custom_29
,rep_entry_custom_30
,rep_entry_custom_31
,rep_entry_custom_32
,rep_entry_custom_33
,rep_entry_custom_34
,rep_entry_custom_35
,rep_entry_custom_36
,rep_entry_custom_37
,rep_entry_custom_38
,rep_entry_custom_39
,rep_entry_custom_40
,CAST(rep_entry_txn_amt AS NUMERIC)
,CAST(rep_entry_posted_amt  AS NUMERIC)
,CAST(rep_entry_approved_amt AS NUMERIC)
,CAST(future_use_5    AS NUMERIC)
,attendee_key
,attendee_unique_idn
,attendee_type_name
,attendee_type_cd
,attendee_last_name
,attendee_first_name
,attendee_compny_name
,attendee_title
,CAST(attendee_ytd_amt    AS NUMERIC)
,CAST(attendee_prev_year_amt  AS NUMERIC)
,attendee_curncy_alpha_cd
,attendee_custom_1
,attendee_custom_2
,attendee_custom_3
,attendee_custom_4
,attendee_custom_5
,attendee_custom_6
,attendee_custom_7
,attendee_custom_8
,attendee_custom_9
,attendee_custom_10
,attendee_custom_11
,attendee_custom_12
,attendee_custom_13
,attendee_custom_14
,attendee_custom_15
,attendee_custom_16
,attendee_custom_17
,attendee_custom_18
,attendee_custom_19
,attendee_custom_20
,CAST(attendee_txn_amt                AS NUMERIC)
,CAST(reimbcurncy_attendee_apprvd_amt AS NUMERIC)
,CAST(curncy_attendee_approved_amt    AS NUMERIC)
,cast(attendee_instance_cnt as numeric)
,attendee_amt_is_edited
,attendee_entry_custom_1
,attendee_entry_custom_2
,attendee_entry_custom_3
,attendee_entry_custom_4
,attendee_entry_custom_5
,attendee_midle_initial
,attendee_suffix
,expense_locatn_cntry_cd
,expense_locatn_state
,expense_locatn_city_name
,attendee_custom_21
,attendee_custom_22
,attendee_custom_23
,attendee_custom_24
,attendee_custom_25
,future_use_6
,future_use_7
,future_use_8
,future_use_9
,future_use_10
,future_use_11
,future_use_12
,future_use_13
,future_use_14
,future_use_15
,future_use_16
,future_use_17
,future_use_18
,future_use_19
,future_use_20
,future_use_21
,future_use_22
,future_use_23
,future_use_24
,future_use_25
,future_use_26
,future_use_27
,future_use_28
,future_use_29
,future_use_30
,future_use_31
,future_use_32
,future_use_33
,future_use_34
,future_use_35
,future_use_36
,future_use_37
,future_use_38
,future_use_39
,future_use_40
,future_use_41
,future_use_42
,future_use_43
,future_use_44
,future_use_45
,future_use_46
,future_use_47
,future_use_48
,future_use_49
,future_use_50
,future_use_51
,future_use_52
,future_use_53
,future_use_54
,future_use_55
,future_use_56
,future_use_57
,(batch_constant||'~'||batch_id||'~'||TO_DATE(batch_dt,'YYYY-MM-DD')||'~'||batch_seq_nbr)
,'CON'
,'fin_tne_mtd_etl_scripts~fin_con_fact_stg'
,'fin_tne_mtd_etl_scripts~fin_con_fact_stg'
,current_timestamp  
,current_timestamp 
from og_file_src.fin_tne_attendee_dtl_extract ;
